var files_dup =
[
    [ "CollisionLogic.h", "_collision_logic_8h_source.html", null ],
    [ "Color.h", "_color_8h_source.html", null ],
    [ "CombatLogic.h", "_combat_logic_8h_source.html", null ],
    [ "Component.h", "_component_8h_source.html", null ],
    [ "DamageOverTime.h", "_damage_over_time_8h_source.html", null ],
    [ "Diagnostics.h", "_diagnostics_8h_source.html", null ],
    [ "DisplayLogic.h", "_display_logic_8h_source.html", null ],
    [ "DoorLogic.h", "_door_logic_8h_source.html", null ],
    [ "GameManager.h", "_game_manager_8h_source.html", null ],
    [ "GameObject.h", "_game_object_8h_source.html", null ],
    [ "Globals.h", "_globals_8h_source.html", null ],
    [ "Inventory.h", "_inventory_8h_source.html", null ],
    [ "ItemLogic.h", "_item_logic_8h_source.html", null ],
    [ "LineOfSight.h", "_line_of_sight_8h_source.html", null ],
    [ "Map.h", "_map_8h_source.html", null ],
    [ "Matrix.h", "_matrix_8h_source.html", null ],
    [ "MessageLog.h", "_message_log_8h_source.html", null ],
    [ "MonsterLogic.h", "_monster_logic_8h_source.html", null ],
    [ "NoiseAndRandom.h", "_noise_and_random_8h_source.html", null ],
    [ "Packet.h", "_packet_8h_source.html", null ],
    [ "Pathfinding.h", "_pathfinding_8h_source.html", null ],
    [ "PlayerInput.h", "_player_input_8h_source.html", null ],
    [ "RoguelikeFoundation.h", "_roguelike_foundation_8h_source.html", null ],
    [ "Sounds.h", "_sounds_8h_source.html", null ],
    [ "StatusEffect.h", "_status_effect_8h_source.html", null ],
    [ "TrapLogic.h", "_trap_logic_8h_source.html", null ],
    [ "UI_Element.h", "_u_i___element_8h_source.html", null ],
    [ "Utility.h", "_utility_8h_source.html", null ],
    [ "Vector2.h", "_vector2_8h_source.html", null ],
    [ "Window.h", "_window_8h_source.html", null ],
    [ "WizardMode.h", "_wizard_mode_8h_source.html", null ]
];